name: publish-python-package

on:
    workflow_call:
        inputs:
            version:
                required: true
                type: string
                description: "PEP440 version string"
            registry:
                required: false
                type: string
                description: "Publish registry (pypi or test-pypi)"
                default: "test-pypi"
            python_version:
                required: false
                type: string
                description: "Python version"
        secrets:
            PYPI_API_TOKEN:
                required: true

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: set-python-version
              run: echo "${{ inputs.python_version }}" > .python-version

            - name: setup-mise
              uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1

            - name: install-dependencies
              run: uv sync --all-extras --all-groups --frozen

            - name: setup-path
              run: echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

            - name: publish
              run: |
                  BAKE_PUBLISH_TOKEN=${{ secrets.PYPI_API_TOKEN }} \
                  bake publish \
                      --registry "${{ inputs.registry }}" \
                      --version "${{ inputs.version }}"
